"""Render docs/RDL-RULES.md from metadata/rules/rdl-rules.json.

    python tools/generate_rdl_rules_doc.py          # rewrite the doc
    python tools/generate_rdl_rules_doc.py --check  # exit 1 if it is stale

The catalog is the source of truth; the doc is generated so the rule table
and its source links cannot drift. tests/test_rdl_documentation.py runs the
same comparison.
"""

import json
import sys
from pathlib import Path
from urllib.parse import urlparse

REPO = Path(__file__).resolve().parent.parent
CATALOG = REPO / "src" / "fab_test" / "metadata" / "rules" / "rdl-rules.json"
DOC = REPO / "docs" / "RDL-RULES.md"
RULE_SET = REPO / "plan" / "rdl-rule-set.md"

_HEADER = """# RDL rules

<!-- Generated by tools/generate_rdl_rules_doc.py from rdl-rules.json. Do not edit by hand. -->

`fab-test rdl` checks paginated (`.rdl`) reports against the **active** rules
below. A rule is active once it trips a real Report Builder file named for it
(`.fabric/artifacts/rdl/<RULE-ID>.rdl`); until then it is planned and does not
run or appear in your results. Each rule links to the guidance it comes from,
and the same links ship in the JSON envelope as `source_urls` on every finding
and `test_results` row.

Severity `error` fails the run; `warning` does not. Tune any rule with a
`rules.rdl` overlay in `fab-test.yml` (see
[Rule Overlays](../.github/skills/fab-test/references/configuration.md)).

| Rule | Name | Severity | Sources |
|------|------|----------|---------|
"""

_PLANNED_HEADER = """
## Planned rules

These rules are in the full rule set ([plan/rdl-rule-set.md](../plan/rdl-rule-set.md))
but **do not run yet** and never show in a run's results. Tier A rules already
have a check and wait for a real fixture; Tier B needs richer analysis than a
presence check; Tier C is manual review or a deployment check rather than XML
analysis.

| Rule | Name | Tier | What it would check | Source |
|------|------|------|---------------------|--------|
"""

_FOOTER = """
## Reading a finding

A finding names where the problem is and what was found:

- **Object** is a path through the report, `Outer › Inner`: `DataSet1 › Test` for
  a calculated field, `Tablix1 › Textbox3` for a textbox inside a table. A
  top-level item is just its name.
- **Message** quotes the offending query, filter or expression (a fragment, not the whole thing), so
  a CI annotation, which shows only the message, still identifies it.
- A rule that fires on several elements gives one row per hit in the report's
  Results table.
- `fab-test rdl --verbose` prints the findings as a Rule / Severity / Object /
  Message table; long cells wrap onto further lines rather than being cut.

## Testing the rules

Real fixtures live in `.fabric/artifacts/rdl/`, one file per rule named for it
(`DS-02.rdl` exists to violate DS-02). `tests/test_rdl_rule_status.py` requires
every active rule to have a check and a fixture that trips it, so a rule cannot
become active without one, and `tests/test_rdl_fixture_rules.py` checks each
fixture against the rule in its name. A fixture for a rule with no check yet is
an expected failure, so the test flips when the check is added. Promoting a
rule is one change: add its fixture, then set `"status": "active"` in
`rdl-rules.json`. The planned rules are tracked in
[tasks/rdl-rule-coverage-epic.md](../tasks/rdl-rule-coverage-epic.md).
"""


def _label(url: str) -> str:
    host = urlparse(url).netloc
    return "MSSQLTips" if "mssqltips" in host else "MS Learn"


def _cell(rule: dict) -> str:
    links = [f"[{_label(u)}]({u})" for u in rule.get("source_urls", [])]
    # The catalog's own source text names rules and authors; keep it so a
    # source without a URL (DMC, DataTaal) is still credited.
    return f"{rule['source']}<br>{' · '.join(links)}" if links else rule["source"]


def _planned(rules: list[dict]) -> list[str]:
    """Planned rows: every rule-set rule that is not active in the catalog.

    The rule-set table supplies the tier and what the rule would check; a
    rule that is already in the catalog as planned keeps its source links.
    """
    active = {r["id"] for r in rules if r.get("status", "active") == "active"}
    in_catalog = {r["id"]: r for r in rules}
    rows = []
    for line in RULE_SET.read_text(encoding="utf-8").splitlines():
        if not line.startswith("| ") or line.startswith("| ID"):
            continue
        # | ID | Rule | Check | Sev | Tier | Source | -- the check text is
        # free-form, so split the fixed columns off both ends.
        rule_id, rest = line.strip("| ").split(" | ", 1)
        name, rest = rest.split(" | ", 1)
        check, _sev, tier, source = rest.rsplit(" | ", 3)
        if rule_id in active:
            continue
        if rule_id in in_catalog:
            name, source = in_catalog[rule_id]["name"], _cell(in_catalog[rule_id])
        rows.append(f"| {rule_id} | {name} | {tier} | {check} | {source} |")
    return rows


def render() -> str:
    rules = json.loads(CATALOG.read_text(encoding="utf-8"))["rules"]
    rows = [
        f"| {r['id']} | {r['name']} | {r['severity']} | {_cell(r)} |"
        for r in rules
        if r.get("status", "active") == "active"
    ]
    planned = _planned(rules)
    return _HEADER + "\n".join(rows) + "\n" + _PLANNED_HEADER + "\n".join(planned) + "\n" + _FOOTER


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if DOC.exists() and DOC.read_text(encoding="utf-8") == text else 1)
    DOC.write_text(text, encoding="utf-8", newline="\n")
